/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AirwaybillView (
  airwaybillId: Option[String],
  airwaybillPrefix: Option[String],
  airwaybillSerial: Option[String],
  pieces: Option[Int],
  weight: Option[AmountUnit],
  voulume: Option[AmountUnit],
  rcvdPieces: Option[Int],
  rcvdWeight: Option[AmountUnit],
  rcvdVolume: Option[AmountUnit],
  previouslyRcvdPieces: Option[Int],
  previouslyRcvdWeight: Option[Double],
  origin: Option[String],
  destination: Option[String],
  location: Option[String],
  preferredLocation: Option[String],
  defaultLocation: Option[String],
  acceptanceStatus: Option[String],
  dimension: Option[Dimension],
  specialHandling: Option[SHC],
  oci: Option[OCI],
  handlingInformation: Option[HandlingInformation],
  remarks: Option[String],
  euPallets: Option[Int],
  waitForTotalStatus: Option[String],
  isMaster: Option[Boolean],
  doneXray: Option[Boolean],
  sendFsu: Option[Boolean],
  isBUP: Option[Boolean],
  readyForCarriageChecked: Option[Boolean],
  blockedForManifesting: Option[Boolean],
  houseAirwaybill: Option[Seq[HouseAirwaybillView]],
  numberOfParts: Option[Int],
  part: Option[Seq[AirwaybillPart]]
) extends ApiModel


